### PR TITLE
Set false instead of null if isAuthenticated is false.

### PR DESCRIPTION
**Pull request by millette**
I'm using EJS for my views and have to use code similar to

``` js
<% if (typeof credentials === 'object' && credentials && credentials.FIELD) { %>
```

If we set `credentials` to FALSE instead of null, template code will be simpler:

``` js
<% if (credentials && credentials.FIELD) { %>
```

### CODE REVIEW

**Comment by mtharrison** [comment]
It should work with `null` too though. Does ejs not treat `null` as a falsy value in comparisons?

**Comment by millette** [comment]
Maybe I'm using it wrong, missing setting or what, but when we set `credentials = null` EJS complains of undefined variables.

**Comment by millette** [comment]
Setting it to false or {} (instead of null) should work everywhere too (unless you were specifically testing for null).

UPDATE: proof of my confusion, {} was a poor suggestion.

**Comment by mtharrison** [comment]
`{}` is not going to work because it's common with this plugin to just check `credentials` is truthy to determine if user is logged in.

Can you provide a verifiable working example where this doesn't work? I did a quick check with Ejs:

``` js
const Ejs = require('ejs');

const templateStr = `<% if (credentials) { %><%= credentials.name %><% } else {%>Nobody<% } %>`;

const template = Ejs.compile(templateStr);
console.log(1, template({ credentials: null }));
console.log(2, template({ credentials: {} }));
console.log(3, template({ credentials: { name: 'Bob'} }));

// 1 'Nobody'
// 2 ''
// 3 'Bob'
```

This is the expected behavior and shouldn't cause issues with this plugin.

**Comment by millette** [comment]
Ok, so I was doing it wrong. <del>I had a 3rd condition and that was failing.</del> Sorry for the noise. I must be confused this morning. Closing.

UPDATE: After testing your demo above, I reverted changes on my end, only to have to problem reappear. Maybe it has to do with vision, visionnary or hapi, I'm still 100% confused :-) I'll open another issue when my head is clear and I can replicate the problem with a simple example.

**Comment by millette** [comment]
I tracked my problem to another preResponse hook (I'm still not very familiar with hapi) I was using to show boom errors as html and the credentials var wasn't set by your module yet.

**Comment by mtharrison** [comment]
Extension dependencies can be managed through the `before` and `after` [`server.ext()`](http://hapijs.com/api#serverextevents) options in hapi. You can probably add `hapi-context-credentials` as an `after` on your other ext.

**Pull request closed without merging**
